# server conf
server:
    port: 18001
    servlet:
        context-path: /

spring:
    # json
    jackson:
        default-property-inclusion: non_null
        date-format: yyyy-MM-dd HH:mm:ss
    # database conf
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&&serverTimezone=GMT
        username: root
        password: 123456
    redis:
        host: 127.0.0.1
        port: 6379
        password: foobared
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: -1

# mybatis conf
mybatis:
    mapperLocations: classpath*:default/mapper/**/*.xml
    typeAliasesPackage: com.shawn.**.entity
    showSql: false

# paging
paging:
  pageNoKey: pageNo
  pageSizeKey: pageSize

logging:
    file:
        name: jooo_admin.log
    level:
        root: debug

app:

    sign:
        check: true
        secret: 1234567890
    host: localhost
    prefix: jooo
    cache:
        prefix: externdevice
        expireTime: 600
